# Generated by Django 3.2.11 on 2022-01-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app_task1.user",
                    ),
                ),
            ],
            bases=("app_task1.user",),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app_task1.user",
                    ),
                ),
            ],
            bases=("app_task1.user",),
        ),
        migrations.CreateModel(
            name="HomeworkResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("solution", models.TextField()),
                ("created", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_task1.homework")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_task1.student")),
            ],
        ),
        migrations.CreateModel(
            name="HomeworkDone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "homework_result",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_task1.homeworkresult"),
                ),
            ],
        ),
    ]
