# Generated by Django 3.2.11 on 2022-01-04 23:48

from django.db import migrations


def load_data(apps, schema_editor):
    teacher = apps.get_model("learning_data", "Teacher")
    student = apps.get_model("learning_data", "Student")

    teacher(name="Alex", last_name="Smith").save()
    teacher(name="Alex", last_name="Black").save()

    student(name="Bob", last_name="Baker").save()
    student(name="Ned", last_name="White").save()
    student(name="George", last_name="Grey").save()


class Migration(migrations.Migration):

    dependencies = [
        ("learning_data", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_data)]
