# Generated by Django 3.2.11 on 2022-01-04 20:29

from django.db import migrations


def load_data(apps, schema_editor):
    teacher = apps.get_model("learning_data", "Teacher")
    student = apps.get_model("learning_data", "Student")

    teacher(name="Alex", deadline="Smith").save()
    teacher(name="Alex", deadline="Black").save()

    student(name="Bob", deadline="Baker").save()
    student(name="Ned", deadline="White").save()
    student(name="George", deadline="Grey").save()


class Migration(migrations.Migration):

    dependencies = [
        ("learning_data", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_data)]
