# This is a basic workflow to help you get started with Actions1111

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install flake8 isort pytest pytest-freezegun
          ls -la
          flake8 .
          isort --profile black --check .
          py.test -v
